# Generated by Django 5.1.4 on 2026-09-05 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingDailyStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("views", models.PositiveIntegerField(default=0)),
                ("contacts", models.PositiveIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_stats",
                        to="catalog.listing",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("listing", "date")},
            },
        ),
        migrations.CreateModel(
            name="ListingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("view", "view"),
                            ("call", "call"),
                            ("whatsapp", "whatsapp"),
                            ("message", "message"),
                            ("share", "share"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ip_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="catalog.listing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listing_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["listing", "kind", "created_at"],
                        name="analytics_l_listing_228637_idx",
                    ),
                    models.Index(
                        fields=["listing", "ip_hash", "kind", "created_at"],
                        name="analytics_l_listing_8c74f1_idx",
                    ),
                ],
            },
        ),
    ]
