# Generated by Django 5.1.4 on 2026-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StaticPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("title_ar", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                ("body_ar", models.TextField(blank=True)),
                ("body_en", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
    ]
