# Generated by Django 5.1.4 on 2026-09-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("listing_approved", "listing_approved"),
                    ("listing_rejected", "listing_rejected"),
                    ("new_message", "new_message"),
                    ("promotion_expiring", "promotion_expiring"),
                    ("broadcast", "broadcast"),
                ],
                max_length=30,
            ),
        ),
    ]
