# Generated by Django 5.1.4 on 2026-09-05 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('center_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('center_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('property_type', models.CharField(choices=[('house', 'منزل'), ('apartment', 'شقة'), ('shop', 'محل'), ('land', 'أرض'), ('other', 'أخرى')], max_length=10)),
                ('purpose', models.CharField(choices=[('sale', 'للبيع'), ('rent', 'للإيجار')], max_length=5)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة'), ('published', 'منشور'), ('rejected', 'مرفوض'), ('sold', 'مباع'), ('rented', 'مؤجر'), ('paused', 'معلق')], default='draft', max_length=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('contacts_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('neighborhood', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.neighborhood')),
            ],
            options={
                'ordering': ['-is_featured', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='listings/thumbnails/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.listing')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.listing')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'listing')},
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'published_at'], name='catalog_lis_status_7f6b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['lat', 'lng'], name='catalog_lis_lat_ad74fb_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['purpose', 'property_type'], name='catalog_lis_purpose_2ba8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['neighborhood', 'status'], name='catalog_lis_neighbo_53995f_idx'),
        ),
    ]
