# Generated by Django 5.1.4 on 2026-09-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingQuotaSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("seeker", models.PositiveIntegerField(default=0)),
                ("owner", models.PositiveIntegerField(default=10)),
                ("agency", models.PositiveIntegerField(default=100)),
            ],
            options={
                "verbose_name": "Listing quota settings",
                "verbose_name_plural": "Listing quota settings",
            },
        ),
    ]
