# Generated by Django 5.1.4 on 2026-09-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="block_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
